# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Download Data

on:
  # At the end of every day
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --save xmlhttprequest      
    - run: node updateData.js
    - run: |
          git config user.name kudjieRaymond
          git config user.email rkudjie@gmaol.com
          git add ./docs/assets/data/*
          git commit -m "update data"
          git push
